# Generated by Django 3.1.7 on 2021-03-31 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWithKakao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kakao_id', models.IntegerField()),
                ('nickname', models.CharField(max_length=225, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
