# Generated by Django 3.2 on 2021-04-08 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_pk', models.AutoField(primary_key=True, serialize=False)),
                ('kakao_id', models.IntegerField()),
                ('nickname', models.CharField(max_length=40, null=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255, null=True)),
                ('country_from', models.CharField(max_length=255, null=True)),
                ('item_currency', models.CharField(max_length=255, null=True)),
                ('shipping_currency', models.CharField(max_length=255, null=True)),
                ('etc_currency', models.CharField(max_length=255, null=True)),
                ('shipping_fee_from', models.IntegerField()),
                ('shipping_fee_to', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('price', models.IntegerField()),
                ('last_price', models.IntegerField()),
                ('purchase_price', models.IntegerField()),
                ('etc_price', models.IntegerField()),
                ('smart_sotre_rate', models.IntegerField()),
                ('e_commerce_rate', models.IntegerField()),
                ('credit_card_rate', models.IntegerField()),
                ('settlement_amount', models.IntegerField()),
                ('User_pk', models.ForeignKey(db_column='User_pk', on_delete=django.db.models.deletion.CASCADE, to='smart_store_solution.user')),
            ],
            options={
                'db_table': 'Merchandises',
            },
        ),
    ]
