# Generated by Django 3.1.7 on 2021-04-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_store_solution', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='User_pk',
        ),
    ]
