# Generated by Django 3.1.7 on 2021-03-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_store_solution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithkakao',
            name='nickname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
