# Generated by Django 3.1.7 on 2021-03-31 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_store_solution', '0003_remove_userwithkakao_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userwithkakao',
            table='user',
        ),
    ]
