# Generated by Django 3.1.7 on 2021-03-31 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_store_solution', '0004_auto_20210331_1248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserWithKakao',
            new_name='User',
        ),
    ]
