# Generated by Django 3.1.7 on 2021-03-31 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_store_solution', '0005_auto_20210331_1253'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
