# Generated by Django 3.1.7 on 2021-03-31 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_store_solution', '0006_auto_20210331_1254'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
