# Generated by Django 3.1.7 on 2021-04-01 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_store_solution', '0007_auto_20210331_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255, null=True)),
                ('price', models.IntegerField()),
                ('country_from', models.CharField(max_length=255, null=True)),
                ('shipping_fee_from', models.IntegerField()),
                ('last_price', models.IntegerField()),
                ('smart_sotre_rate', models.IntegerField()),
                ('real_price', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('e_commerce_rate', models.IntegerField()),
                ('credit_card_rate', models.IntegerField()),
                ('purchase_price', models.IntegerField()),
                ('shipping_fee_to', models.IntegerField()),
                ('ect_price', models.IntegerField()),
                ('item_currency', models.CharField(max_length=255, null=True)),
                ('shipping_currency', models.CharField(max_length=255, null=True)),
                ('etc_currency', models.CharField(max_length=255, null=True)),
                ('User_id', models.ForeignKey(db_column='User_id', on_delete=django.db.models.deletion.CASCADE, to='smart_store_solution.user')),
            ],
            options={
                'db_table': 'Merchandises',
            },
        ),
    ]
