# Generated by Django 3.1.7 on 2021-04-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_store_solution', '0008_auto_20210401_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchandise',
            old_name='ect_price',
            new_name='etc_price',
        ),
        migrations.RenameField(
            model_name='merchandise',
            old_name='real_price',
            new_name='settlement_amount',
        ),
    ]
